### ISSUE TITLE
To File Extension Name

### ISSUE THREAD

**Issue by Himanshuch8055** [yashsharma8433/LEETCODE-DAILY-CHALLENGE#1]
Hi Yash, my name is Himanshu. I see your Repo [LEETCODE-DAILY-CHALLENGE] (https://github.com/yashsharma8433/LEETCODE-DAILY-CHALLENGE) there is an issue to file extension.
Save file with file extension (Like your file in Java so add file extension .java)
.
.
Same Issues Here.

**Comment by yashsharma8433** [comment]
Hlo Himanshu,Hope you doing well. Could You please make changes.

**Comment by Himanshuch8055** [comment]
Sure 😸

**Comment by yashsharma8433** [comment]
ok i will assign you  this.

**Comment by yashsharma8433** [comment]
ISSUE SOLVED I AM CLOSING THIS ISSUE
